# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    default_locale: pl
    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - pl

    session: true

